<?php

namespace App\Lib;

class Data
{
    public static function getCountriesList() {
        return [
            'AF' => ['name' => 'Afghanistan', 'flag' => 'flags/afghanistan.svg'],
            'AX' => ['name' => 'Aland Islands', 'flag' => 'flags/aland-islands.svg'],
            'AL' => ['name' => 'Albania', 'flag' => 'flags/albania.svg'],
            'DZ' => ['name' => 'Algeria', 'flag' => 'flags/algeria.svg'],
            'AS' => ['name' => 'American Samoa', 'flag' => 'flags/american-samoa.svg'],
            'AD' => ['name' => 'Andorra', 'flag' => 'flags/andorra.svg'],
            'AO' => ['name' => 'Angola', 'flag' => 'flags/angola.svg'],
            'AI' => ['name' => 'Anguilla', 'flag' => 'flags/anguilla.svg'],
            'AG' => ['name' => 'Antigua and Barbuda', 'flag' => 'flags/antigua-and-barbuda.svg'],
            'AR' => ['name' => 'Argentina', 'flag' => 'flags/argentina.svg'],
            'AM' => ['name' => 'Armenia', 'flag' => 'flags/armenia.svg'],
            'AW' => ['name' => 'Aruba', 'flag' => 'flags/aruba.svg'],
            'AU' => ['name' => 'Australia', 'flag' => 'flags/australia.svg'],
            'AT' => ['name' => 'Austria', 'flag' => 'flags/austria.svg'],
            'AZ' => ['name' => 'Azerbaijan', 'flag' => 'flags/azerbaijan.svg'],
            'BS' => ['name' => 'Bahamas', 'flag' => 'flags/bahamas.svg'],
            'BH' => ['name' => 'Bahrain', 'flag' => 'flags/bahrain.svg'],
            'BD' => ['name' => 'Bangladesh', 'flag' => 'flags/bangladesh.svg'],
            'BB' => ['name' => 'Barbados', 'flag' => 'flags/barbados.svg'],
            'BY' => ['name' => 'Belarus', 'flag' => 'flags/belarus.svg'],
            'BE' => ['name' => 'Belgium', 'flag' => 'flags/belgium.svg'],
            'BZ' => ['name' => 'Belize', 'flag' => 'flags/belize.svg'],
            'BJ' => ['name' => 'Benin', 'flag' => 'flags/benin.svg'],
            'BM' => ['name' => 'Bermuda', 'flag' => 'flags/bermuda.svg'],
            'BT' => ['name' => 'Bhutan', 'flag' => 'flags/bhutan.svg'],
            'BO' => ['name' => 'Bolivia, Plurinational State of', 'flag' => 'flags/bolivia.svg'],
            'BQ' => ['name' => 'Bonaire, Sint Eustatius and Saba', 'flag' => 'flags/bonaire.svg'],
            'BA' => ['name' => 'Bosnia and Herzegovina', 'flag' => 'flags/bosnia-and-herzegovina.svg'],
            'BW' => ['name' => 'Botswana', 'flag' => 'flags/botswana.svg'],
            'BR' => ['name' => 'Brazil', 'flag' => 'flags/brazil.svg'],
            'IO' => ['name' => 'British Indian Ocean Territory', 'flag' => 'flags/british-indian-ocean-territory.svg'],
            'BN' => ['name' => 'Brunei Darussalam', 'flag' => 'flags/brunei.svg'],
            'BG' => ['name' => 'Bulgaria', 'flag' => 'flags/bulgaria.svg'],
            'BF' => ['name' => 'Burkina Faso', 'flag' => 'flags/burkina-faso.svg'],
            'BI' => ['name' => 'Burundi', 'flag' => 'flags/burundi.svg'],
            'KH' => ['name' => 'Cambodia', 'flag' => 'flags/cambodia.svg'],
            'CM' => ['name' => 'Cameroon', 'flag' => 'flags/cameroon.svg'],
            'CA' => ['name' => 'Canada', 'flag' => 'flags/canada.svg'],
            'CV' => ['name' => 'Cape Verde', 'flag' => 'flags/cape-verde.svg'],
            'KY' => ['name' => 'Cayman Islands', 'flag' => 'flags/cayman-islands.svg'],
            'CF' => ['name' => 'Central African Republic', 'flag' => 'flags/central-african-republic.svg'],
            'TD' => ['name' => 'Chad', 'flag' => 'flags/chad.svg'],
            'CL' => ['name' => 'Chile', 'flag' => 'flags/chile.svg'],
            'CN' => ['name' => 'China', 'flag' => 'flags/china.svg'],
            'CX' => ['name' => 'Christmas Island', 'flag' => 'flags/christmas-island.svg'],
            'CC' => ['name' => 'Cocos (Keeling) Islands', 'flag' => 'flags/cocos-island.svg'],
            'CO' => ['name' => 'Colombia', 'flag' => 'flags/colombia.svg'],
            'KM' => ['name' => 'Comoros', 'flag' => 'flags/comoros.svg'],
            'CK' => ['name' => 'Cook Islands', 'flag' => 'flags/cook-islands.svg'],
            'CR' => ['name' => 'Costa Rica', 'flag' => 'flags/costa-rica.svg'],
            'CI' => ['name' => 'Côte d\'Ivoire', 'flag' => 'flags/ivory-coast.svg'],
            'HR' => ['name' => 'Croatia', 'flag' => 'flags/croatia.svg'],
            'CU' => ['name' => 'Cuba', 'flag' => 'flags/cuba.svg'],
            'CW' => ['name' => 'Curaçao', 'flag' => 'flags/curacao.svg'],
            'CZ' => ['name' => 'Czech Republic', 'flag' => 'flags/czech-republic.svg'],
            'DK' => ['name' => 'Denmark', 'flag' => 'flags/denmark.svg'],
            'DJ' => ['name' => 'Djibouti', 'flag' => 'flags/djibouti.svg'],
            'DM' => ['name' => 'Dominica', 'flag' => 'flags/dominica.svg'],
            'DO' => ['name' => 'Dominican Republic', 'flag' => 'flags/dominican-republic.svg'],
            'EC' => ['name' => 'Ecuador', 'flag' => 'flags/ecuador.svg'],
            'EG' => ['name' => 'Egypt', 'flag' => 'flags/egypt.svg'],
            'SV' => ['name' => 'El Salvador', 'flag' => 'flags/el-salvador.svg'],
            'GQ' => ['name' => 'Equatorial Guinea', 'flag' => 'flags/equatorial-guinea.svg'],
            'ER' => ['name' => 'Eritrea', 'flag' => 'flags/eritrea.svg'],
            'EE' => ['name' => 'Estonia', 'flag' => 'flags/estonia.svg'],
            'ET' => ['name' => 'Ethiopia', 'flag' => 'flags/ethiopia.svg'],
            'FK' => ['name' => 'Falkland Islands (Malvinas)', 'flag' => 'flags/falkland-islands.svg'],
            'FJ' => ['name' => 'Fiji', 'flag' => 'flags/fiji.svg'],
            'FI' => ['name' => 'Finland', 'flag' => 'flags/finland.svg'],
            'FR' => ['name' => 'France', 'flag' => 'flags/france.svg'],
            'PF' => ['name' => 'French Polynesia', 'flag' => 'flags/french-polynesia.svg'],
            'GA' => ['name' => 'Gabon', 'flag' => 'flags/gabon.svg'],
            'GM' => ['name' => 'Gambia', 'flag' => 'flags/gambia.svg'],
            'GE' => ['name' => 'Georgia', 'flag' => 'flags/georgia.svg'],
            'DE' => ['name' => 'Germany', 'flag' => 'flags/germany.svg'],
            'GH' => ['name' => 'Ghana', 'flag' => 'flags/ghana.svg'],
            'GI' => ['name' => 'Gibraltar', 'flag' => 'flags/gibraltar.svg'],
            'GR' => ['name' => 'Greece', 'flag' => 'flags/greece.svg'],
            'GL' => ['name' => 'Greenland', 'flag' => 'flags/greenland.svg'],
            'GD' => ['name' => 'Grenada', 'flag' => 'flags/grenada.svg'],
            'GU' => ['name' => 'Guam', 'flag' => 'flags/guam.svg'],
            'GT' => ['name' => 'Guatemala', 'flag' => 'flags/guatemala.svg'],
            'GG' => ['name' => 'Guernsey', 'flag' => 'flags/guernsey.svg'],
            'GN' => ['name' => 'Guinea', 'flag' => 'flags/guinea.svg'],
            'GW' => ['name' => 'Guinea-Bissau', 'flag' => 'flags/guinea-bissau.svg'],
            'HT' => ['name' => 'Haiti', 'flag' => 'flags/haiti.svg'],
            'VA' => ['name' => 'Holy See (Vatican City State)', 'flag' => 'flags/vatican-city.svg'],
            'HN' => ['name' => 'Honduras', 'flag' => 'flags/honduras.svg'],
            'HK' => ['name' => 'Hong Kong', 'flag' => 'flags/hong-kong.svg'],
            'HU' => ['name' => 'Hungary', 'flag' => 'flags/hungary.svg'],
            'IS' => ['name' => 'Iceland', 'flag' => 'flags/iceland.svg'],
            'IN' => ['name' => 'India', 'flag' => 'flags/india.svg'],
            'ID' => ['name' => 'Indonesia', 'flag' => 'flags/indonesia.svg'],
            'IR' => ['name' => 'Iran, Islamic Republic of', 'flag' => 'flags/iran.svg'],
            'IQ' => ['name' => 'Iraq', 'flag' => 'flags/iraq.svg'],
            'IE' => ['name' => 'Ireland', 'flag' => 'flags/ireland.svg'],
            'IM' => ['name' => 'Isle of Man', 'flag' => 'flags/isle-of-man.svg'],
            'IL' => ['name' => 'Israel', 'flag' => 'flags/israel.svg'],
            'IT' => ['name' => 'Italy', 'flag' => 'flags/italy.svg'],
            'JM' => ['name' => 'Jamaica', 'flag' => 'flags/jamaica.svg'],
            'JP' => ['name' => 'Japan', 'flag' => 'flags/japan.svg'],
            'JE' => ['name' => 'Jersey', 'flag' => 'flags/jersey.svg'],
            'JO' => ['name' => 'Jordan', 'flag' => 'flags/jordan.svg'],
            'KZ' => ['name' => 'Kazakhstan', 'flag' => 'flags/kazakhstan.svg'],
            'KE' => ['name' => 'Kenya', 'flag' => 'flags/kenya.svg'],
            'KI' => ['name' => 'Kiribati', 'flag' => 'flags/kiribati.svg'],
            'KP' => ['name' => 'Korea, Democratic People\'s Republic of', 'flag' => 'flags/north-korea.svg'],
            'KW' => ['name' => 'Kuwait', 'flag' => 'flags/kuwait.svg'],
            'KG' => ['name' => 'Kyrgyzstan', 'flag' => 'flags/kyrgyzstan.svg'],
            'LA' => ['name' => 'Lao People\'s Democratic Republic', 'flag' => 'flags/laos.svg'],
            'LV' => ['name' => 'Latvia', 'flag' => 'flags/latvia.svg'],
            'LB' => ['name' => 'Lebanon', 'flag' => 'flags/lebanon.svg'],
            'LS' => ['name' => 'Lesotho', 'flag' => 'flags/lesotho.svg'],
            'LR' => ['name' => 'Liberia', 'flag' => 'flags/liberia.svg'],
            'LY' => ['name' => 'Libya', 'flag' => 'flags/libya.svg'],
            'LI' => ['name' => 'Liechtenstein', 'flag' => 'flags/liechtenstein.svg'],
            'LT' => ['name' => 'Lithuania', 'flag' => 'flags/lithuania.svg'],
            'LU' => ['name' => 'Luxembourg', 'flag' => 'flags/luxembourg.svg'],
            'MO' => ['name' => 'Macao', 'flag' => 'flags/macao.svg'],
            'MG' => ['name' => 'Madagascar', 'flag' => 'flags/madagascar.svg'],
            'MW' => ['name' => 'Malawi', 'flag' => 'flags/malawi.svg'],
            'MY' => ['name' => 'Malaysia', 'flag' => 'flags/malaysia.svg'],
            'MV' => ['name' => 'Maldives', 'flag' => 'flags/maldives.svg'],
            'ML' => ['name' => 'Mali', 'flag' => 'flags/mali.svg'],
            'MT' => ['name' => 'Malta', 'flag' => 'flags/malta.svg'],
            'MH' => ['name' => 'Marshall Islands', 'flag' => 'flags/marshall-island.svg'],
            'MQ' => ['name' => 'Martinique', 'flag' => 'flags/martinique.svg'],
            'MR' => ['name' => 'Mauritania', 'flag' => 'flags/mauritania.svg'],
            'MU' => ['name' => 'Mauritius', 'flag' => 'flags/mauritius.svg'],
            'MX' => ['name' => 'Mexico', 'flag' => 'flags/mexico.svg'],
            'FM' => ['name' => 'Micronesia, Federated States of', 'flag' => 'flags/micronesia.svg'],
            'MD' => ['name' => 'Moldova, Republic of', 'flag' => 'flags/moldova.svg'],
            'MC' => ['name' => 'Monaco', 'flag' => 'flags/monaco.svg'],
            'MN' => ['name' => 'Mongolia', 'flag' => 'flags/mongolia.svg'],
            'ME' => ['name' => 'Montenegro', 'flag' => 'flags/montenegro.svg'],
            'MS' => ['name' => 'Montserrat', 'flag' => 'flags/montserrat.svg'],
            'MA' => ['name' => 'Morocco', 'flag' => 'flags/morocco.svg'],
            'MZ' => ['name' => 'Mozambique', 'flag' => 'flags/mozambique.svg'],
            'MM' => ['name' => 'Myanmar', 'flag' => 'flags/myanmar.svg'],
            'NA' => ['name' => 'Namibia', 'flag' => 'flags/namibia.svg'],
            'NR' => ['name' => 'Nauru', 'flag' => 'flags/nauru.svg'],
            'NP' => ['name' => 'Nepal', 'flag' => 'flags/nepal.svg'],
            'NL' => ['name' => 'Netherlands', 'flag' => 'flags/netherlands.svg'],
            'NZ' => ['name' => 'New Zealand', 'flag' => 'flags/new-zealand.svg'],
            'NI' => ['name' => 'Nicaragua', 'flag' => 'flags/nicaragua.svg'],
            'NE' => ['name' => 'Niger', 'flag' => 'flags/niger.svg'],
            'NG' => ['name' => 'Nigeria', 'flag' => 'flags/nigeria.svg'],
            'NU' => ['name' => 'Niue', 'flag' => 'flags/niue.svg'],
            'NF' => ['name' => 'Norfolk Island', 'flag' => 'flags/norfolk-island.svg'],
            'MP' => ['name' => 'Northern Mariana Islands', 'flag' => 'flags/northern-mariana-islands.svg'],
            'NO' => ['name' => 'Norway', 'flag' => 'flags/norway.svg'],
            'OM' => ['name' => 'Oman', 'flag' => 'flags/oman.svg'],
            'PK' => ['name' => 'Pakistan', 'flag' => 'flags/pakistan.svg'],
            'PW' => ['name' => 'Palau', 'flag' => 'flags/palau.svg'],
            'PS' => ['name' => 'Palestinian Territory, Occupied', 'flag' => 'flags/palestine.svg'],
            'PA' => ['name' => 'Panama', 'flag' => 'flags/panama.svg'],
            'PG' => ['name' => 'Papua New Guinea', 'flag' => 'flags/papua-new-guinea.svg'],
            'PY' => ['name' => 'Paraguay', 'flag' => 'flags/paraguay.svg'],
            'PE' => ['name' => 'Peru', 'flag' => 'flags/peru.svg'],
            'PH' => ['name' => 'Philippines', 'flag' => 'flags/philippines.svg'],
            'PL' => ['name' => 'Poland', 'flag' => 'flags/poland.svg'],
            'PT' => ['name' => 'Portugal', 'flag' => 'flags/portugal.svg'],
            'PR' => ['name' => 'Puerto Rico', 'flag' => 'flags/puerto-rico.svg'],
            'QA' => ['name' => 'Qatar', 'flag' => 'flags/qatar.svg'],
            'RO' => ['name' => 'Romania', 'flag' => 'flags/romania.svg'],
            'RU' => ['name' => 'Russian Federation', 'flag' => 'flags/russia.svg'],
            'RW' => ['name' => 'Rwanda', 'flag' => 'flags/rwanda.svg'],
            'BL' => ['name' => 'Saint Barthélemy', 'flag' => 'flags/st-barts.svg'],
            'KN' => ['name' => 'Saint Kitts and Nevis', 'flag' => 'flags/saint-kitts-and-nevis.svg'],
            'LC' => ['name' => 'Saint Lucia', 'flag' => 'flags/st-lucia.svg'],
            'MF' => ['name' => 'Saint Martin (French part)', 'flag' => 'flags/sint-maarten.svg'],
            // 'PM' => array('name' => 'Saint Pierre and Miquelon', 'flag' => 'flags/saint-pierre.svg'),
            'VC' => ['name' => 'Saint Vincent and the Grenadines', 'flag' => 'flags/st-vincent-and-the-grenadines.svg'],
            'WS' => ['name' => 'Samoa', 'flag' => 'flags/samoa.svg'],
            'SM' => ['name' => 'San Marino', 'flag' => 'flags/san-marino.svg'],
            'ST' => ['name' => 'Sao Tome and Principe', 'flag' => 'flags/sao-tome-and-prince.svg'],
            'SA' => ['name' => 'Saudi Arabia', 'flag' => 'flags/saudi-arabia.svg'],
            'SN' => ['name' => 'Senegal', 'flag' => 'flags/senegal.svg'],
            'RS' => ['name' => 'Serbia', 'flag' => 'flags/serbia.svg'],
            'SC' => ['name' => 'Seychelles', 'flag' => 'flags/seychelles.svg'],
            'SL' => ['name' => 'Sierra Leone', 'flag' => 'flags/sierra-leone.svg'],
            'SG' => ['name' => 'Singapore', 'flag' => 'flags/singapore.svg'],
            'SX' => ['name' => 'Sint Maarten (Dutch part)', 'flag' => 'flags/sint-maarten.svg'],
            'SK' => ['name' => 'Slovakia', 'flag' => 'flags/slovakia.svg'],
            'SI' => ['name' => 'Slovenia', 'flag' => 'flags/slovenia.svg'],
            'SB' => ['name' => 'Solomon Islands', 'flag' => 'flags/solomon-islands.svg'],
            'SO' => ['name' => 'Somalia', 'flag' => 'flags/somalia.svg'],
            'ZA' => ['name' => 'South Africa', 'flag' => 'flags/south-africa.svg'],
            'KR' => ['name' => 'South Korea', 'flag' => 'flags/south-korea.svg'],
            'SS' => ['name' => 'South Sudan', 'flag' => 'flags/south-sudan.svg'],
            'ES' => ['name' => 'Spain', 'flag' => 'flags/spain.svg'],
            'LK' => ['name' => 'Sri Lanka', 'flag' => 'flags/sri-lanka.svg'],
            'SD' => ['name' => 'Sudan', 'flag' => 'flags/sudan.svg'],
            'SR' => ['name' => 'Suriname', 'flag' => 'flags/suriname.svg'],
            'SZ' => ['name' => 'Swaziland', 'flag' => 'flags/swaziland.svg'],
            'SE' => ['name' => 'Sweden', 'flag' => 'flags/sweden.svg'],
            'CH' => ['name' => 'Switzerland', 'flag' => 'flags/switzerland.svg'],
            'SY' => ['name' => 'Syrian Arab Republic', 'flag' => 'flags/syria.svg'],
            'TW' => ['name' => 'Taiwan, Province of China', 'flag' => 'flags/taiwan.svg'],
            'TJ' => ['name' => 'Tajikistan', 'flag' => 'flags/tajikistan.svg'],
            'TZ' => ['name' => 'Tanzania, United Republic of', 'flag' => 'flags/tanzania.svg'],
            'TH' => ['name' => 'Thailand', 'flag' => 'flags/thailand.svg'],
            'TG' => ['name' => 'Togo', 'flag' => 'flags/togo.svg'],
            'TK' => ['name' => 'Tokelau', 'flag' => 'flags/tokelau.svg'],
            'TO' => ['name' => 'Tonga', 'flag' => 'flags/tonga.svg'],
            'TT' => ['name' => 'Trinidad and Tobago', 'flag' => 'flags/trinidad-and-tobago.svg'],
            'TN' => ['name' => 'Tunisia', 'flag' => 'flags/tunisia.svg'],
            'TR' => ['name' => 'Turkey', 'flag' => 'flags/turkey.svg'],
            'TM' => ['name' => 'Turkmenistan', 'flag' => 'flags/turkmenistan.svg'],
            'TC' => ['name' => 'Turks and Caicos Islands', 'flag' => 'flags/turks-and-caicos.svg'],
            'TV' => ['name' => 'Tuvalu', 'flag' => 'flags/tuvalu.svg'],
            'UG' => ['name' => 'Uganda', 'flag' => 'flags/uganda.svg'],
            'UA' => ['name' => 'Ukraine', 'flag' => 'flags/ukraine.svg'],
            'AE' => ['name' => 'United Arab Emirates', 'flag' => 'flags/united-arab-emirates.svg'],
            'GB' => ['name' => 'United Kingdom', 'flag' => 'flags/united-kingdom.svg'],
            'US' => ['name' => 'United States', 'flag' => 'flags/united-states.svg'],
            'UY' => ['name' => 'Uruguay', 'flag' => 'flags/uruguay.svg'],
            'UZ' => ['name' => 'Uzbekistan', 'flag' => 'flags/uzbekistan.svg'],
            'VU' => ['name' => 'Vanuatu', 'flag' => 'flags/vanuatu.svg'],
            'VE' => ['name' => 'Venezuela, Bolivarian Republic of', 'flag' => 'flags/venezuela.svg'],
            'VN' => ['name' => 'Vietnam', 'flag' => 'flags/vietnam.svg'],
            'VI' => ['name' => 'Virgin Islands', 'flag' => 'flags/virgin-islands.svg'],
            'YE' => ['name' => 'Yemen', 'flag' => 'flags/yemen.svg'],
            'ZM' => ['name' => 'Zambia', 'flag' => 'flags/zambia.svg'],
            'ZW' => ['name' => 'Zimbabwe', 'flag' => 'flags/zimbabwe.svg']
        ];
    }

    public static function getLanguagesList() {
        $countryArr = Data::getCountriesList();

        return [
            'id' => ['name' => 'Bahasa Indonesia - Indonesian', 'country' => $countryArr['ID']],
            'msa' => ['name' => 'Bahasa Melayu - Malay', 'country' => $countryArr['MY']],
            'ca' => ['name' => 'Català - Catalan', 'country' => $countryArr['CA']],
            'cs' => ['name' => 'Čeština - Czech', 'country' => $countryArr['CZ']],
            'da' => ['name' => 'Dansk - Danish', 'country' => $countryArr['NL']],
            'de' => ['name' => 'Deutsch - German', 'country' => $countryArr['DE']],
            'en' => ['name' => 'English', 'country' => $countryArr['GB']],
            'en-gb' => ['name' => 'English UK - British English', 'country' => $countryArr['GB']],
            'es' => ['name' => 'Español - Spanish', 'country' => $countryArr['ES']],
            'fil' => ['name' => 'Filipino', 'country' => $countryArr['PH']],
            'fr' => ['name' => 'Français - French', 'country' => $countryArr['FR']],
            'ga' => ['name' => 'Gaeilge - Irish (beta)', 'country' => $countryArr['GA']],
            'gl' => ['name' => 'Galego - Galician (beta)', 'country' => $countryArr['GL']],
            'hr' => ['name' => 'Hrvatski - Croatian', 'country' => $countryArr['HR']],
            'it' => ['name' => 'Italiano - Italian', 'country' => $countryArr['IT']],
            'hu' => ['name' => 'Magyar - Hungarian', 'country' => $countryArr['HU']],
            'nl' => ['name' => 'Nederlands - Dutch', 'country' => $countryArr['NL']],
            'no' => ['name' => 'Norsk - Norwegian', 'country' => $countryArr['NO']],
            'pl' => ['name' => 'Polski - Polish', 'country' => $countryArr['PL']],
            'pt' => ['name' => 'Português - Portuguese', 'country' => $countryArr['PT']],
            'ro' => ['name' => 'Română - Romanian', 'country' => $countryArr['RO']],
            'sk' => ['name' => 'Slovenčina - Slovak', 'country' => $countryArr['SK']],
            'fi' => ['name' => 'Suomi - Finnish', 'country' => $countryArr['FI']],
            'sv' => ['name' => 'Svenska - Swedish', 'country' => $countryArr['SV']],
            'vi' => ['name' => 'Tiếng Việt - Vietnamese', 'country' => $countryArr['VI']],
            'tr' => ['name' => 'Türkçe - Turkish', 'country' => $countryArr['TR']],
            'el' => ['name' => 'Ελληνικά - Greek', 'country' => $countryArr['GR']],
            'bg' => ['name' => 'Български език - Bulgarian', 'country' => $countryArr['BG']],
            'ru' => ['name' => 'Русский - Russian', 'country' => $countryArr['RU']],
            'sr' => ['name' => 'Српски - Serbian', 'country' => $countryArr['SR']],
            'uk' => ['name' => 'Українська мова - Ukrainian', 'country' => $countryArr['UA']],
            'he' => ['name' => 'עִבְרִית - Hebrew', 'country' => $countryArr['IL']],
            'ur' => ['name' => 'اردو - Urdu (beta)', 'country' => $countryArr['PK']],
            'ar' => ['name' => 'العربية - Arabic', 'country' => $countryArr['AR']],
            'fa' => ['name' => 'فارسی - Persian', 'country' => $countryArr['AR']],
            'mr' => ['name' => 'मराठी - Marathi', 'country' => $countryArr['MR']],
            'hi' => ['name' => 'हिन्दी - Hindi', 'country' => $countryArr['IN']],
            'bn' => ['name' => 'বাংলা - Bangla', 'country' => $countryArr['BD']],
            'gu' => ['name' => 'ગુજરાતી - Gujarati', 'country' => $countryArr['GU']],
            'ta' => ['name' => 'தமிழ் - Tamil', 'country' => $countryArr['IN']],
            'kn' => ['name' => 'ಕನ್ನಡ - Kannada', 'country' => $countryArr['KN']],
            'th' => ['name' => 'ภาษาไทย - Thai', 'country' => $countryArr['TH']],
            'ko' => ['name' => '한국어 - Korean', 'country' => $countryArr['KR']],
            'ja' => ['name' => '日本語 - Japanese', 'country' => $countryArr['JP']],
            'zh-cn' => ['name' => '简体中文 - Simplified Chinese', 'country' => $countryArr['CN']],
            'zh-tw' => ['name' => '繁體中文 - Traditional Chinese', 'country' => $countryArr['TW']]
        ];
    }
}
