<?php

namespace Database\Seeders;

use App\Models\Category;
use Illuminate\Database\Seeder;

class CategorySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $categories = array(
            array('id' => '1','name' => 'deposit','slug' => NULL,'type' => 'ReferralCommissionConfig','other' => NULL,'category_id' => NULL,'featured' => '0','menu_status' => '0','status' => '1','lang' => 'en','created_at' => now(),'updated_at' => now()),
            array('id' => '2','name' => 'membership_upgrade','slug' => NULL,'type' => 'ReferralCommissionConfig','other' => NULL,'category_id' => NULL,'featured' => '0','menu_status' => '0','status' => '1','lang' => 'en','created_at' => now(),'updated_at' => now()),
            array('id' => '3','name' => 'ptc_view','slug' => NULL,'type' => 'ReferralCommissionConfig','other' => NULL,'category_id' => NULL,'featured' => '0','menu_status' => '0','status' => '0','lang' => 'en','created_at' => now(),'updated_at' => now()),
            array('id' => '4','name' => 'Earn Money For Simple Work Online','slug' => NULL,'type' => 'heading.welcome','other' => 'For Enhanced performance we use LiteSpeed Web Server, HTTP/2, PHP7. We make your website faster, which will help you to increase search ranking!','category_id' => NULL,'featured' => '0','menu_status' => '0','status' => '1','lang' => 'en','created_at' => now(),'updated_at' => now()),
            array('id' => '5','name' => 'كسب المال مقابل العمل البسيط عبر الإنترنت','slug' => NULL,'type' => 'heading.welcome','other' => 'هناك حقيقة مثبتة منذ زمن طويل وهي أن المحتوى المقروء لصفحة ما سيلهي القارئ عن التركيز على الشكل الخارجي للنص أو شكل توضع الفقرات في الصفحة التي يقرأها','category_id' => NULL,'featured' => '0','menu_status' => '0','status' => '1','lang' => 'ar','created_at' => now(),'updated_at' => now()),
            array('id' => '6','name' => 'GET PAID','slug' => NULL,'type' => 'features','other' => 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s','category_id' => NULL,'featured' => '1','menu_status' => '0','status' => '1','lang' => 'en','created_at' => now(),'updated_at' => now()),
            array('id' => '7','name' => 'EARN MONEY','slug' => NULL,'type' => 'features','other' => 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s','category_id' => NULL,'featured' => '1','menu_status' => '0','status' => '1','lang' => 'en','created_at' => now(),'updated_at' => now()),
            array('id' => '8','name' => 'FREE SIGNUP','slug' => NULL,'type' => 'features','other' => 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s','category_id' => NULL,'featured' => '1','menu_status' => '0','status' => '1','lang' => 'en','created_at' => now(),'updated_at' => now()),
            array('id' => '9','name' => 'Our facilities','slug' => NULL,'type' => 'heading.features','other' => 'It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout.','category_id' => NULL,'featured' => '0','menu_status' => '0','status' => '1','lang' => 'en','created_at' => now(),'updated_at' => now()),
            array('id' => '10','name' => 'منشأتنا','slug' => NULL,'type' => 'heading.features','other' => 'هناك حقيقة مثبتة منذ زمن طويل وهي أن المحتوى المقروء لصفحة ما سيلهي القارئ عن التركيز على الشكل الخارجي للنص أو شكل توضع الفقرات في الصفحة التي يقرأها','category_id' => NULL,'featured' => '0','menu_status' => '0','status' => '1','lang' => 'ar','created_at' => now(),'updated_at' => now()),
            array('id' => '11','name' => 'تسجيل مجاني','slug' => NULL,'type' => 'features','other' => 'هناك حقيقة مثبتة منذ زمن طويل وهي أن المحتوى المقروء لصفحة ما سيلهي القارئ عن التركيز على الشكل الخارجي للنص أو شكل توضع الفقرات في الصفحة التي يقرأها','category_id' => NULL,'featured' => '1','menu_status' => '0','status' => '1','lang' => 'ar','created_at' => now(),'updated_at' => now()),
            array('id' => '12','name' => 'يكتسب نقود','slug' => NULL,'type' => 'features','other' => 'هناك حقيقة مثبتة منذ زمن طويل وهي أن المحتوى المقروء لصفحة ما سيلهي القارئ عن التركيز على الشكل الخارجي للنص أو شكل توضع الفقرات في الصفحة التي يقرأها','category_id' => NULL,'featured' => '1','menu_status' => '0','status' => '1','lang' => 'ar','created_at' => now(),'updated_at' => now()),
            array('id' => '13','name' => 'احصل على الدفع','slug' => NULL,'type' => 'features','other' => 'هناك حقيقة مثبتة منذ زمن طويل وهي أن المحتوى المقروء لصفحة ما سيلهي القارئ عن التركيز على الشكل الخارجي للنص أو شكل توضع الفقرات في الصفحة التي يقرأها','category_id' => NULL,'featured' => '1','menu_status' => '0','status' => '1','lang' => 'ar','created_at' => now(),'updated_at' => now()),
            array('id' => '14','name' => 'Your benefits','slug' => NULL,'type' => 'heading.member_benefits','other' => 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Doloribus necessitatibus repudiandae porro reprehenderit up','category_id' => NULL,'featured' => '0','menu_status' => '0','status' => '1','lang' => 'en','created_at' => now(),'updated_at' => now()),
            array('id' => '15','name' => 'المنافع الخاصة بك','slug' => NULL,'type' => 'heading.member_benefits','other' => 'هناك حقيقة مثبتة منذ زمن طويل وهي أن المحتوى المقروء لصفحة ما سيلهي القارئ عن التركيز على الشكل الخارجي للنص أو شكل توضع الفقرات في الصفحة التي يقرأها','category_id' => NULL,'featured' => '0','menu_status' => '0','status' => '1','lang' => 'ar','created_at' => now(),'updated_at' => now()),
            array('id' => '17','name' => 'Earn up to $0.25 per click','slug' => NULL,'type' => 'member_benefits','other' => NULL,'category_id' => NULL,'featured' => '0','menu_status' => '0','status' => '1','lang' => 'en','created_at' => now(),'updated_at' => now()),
            array('id' => '18','name' => 'Earn up to $0.28 per Referral Click','slug' => NULL,'type' => 'member_benefits','other' => NULL,'category_id' => NULL,'featured' => '0','menu_status' => '0','status' => '1','lang' => 'en','created_at' => now(),'updated_at' => now()),
            array('id' => '19','name' => 'Fast Payment and receving system','slug' => NULL,'type' => 'member_benefits','other' => NULL,'category_id' => NULL,'featured' => '0','menu_status' => '0','status' => '1','lang' => 'en','created_at' => now(),'updated_at' => now()),
            array('id' => '20','name' => 'Earn up to $0.25 per click','slug' => NULL,'type' => 'member_benefits','other' => NULL,'category_id' => NULL,'featured' => '0','menu_status' => '0','status' => '1','lang' => 'en','created_at' => now(),'updated_at' => now()),
            array('id' => '21','name' => 'Earn up to $0.28 per Referral Click','slug' => NULL,'type' => 'member_benefits','other' => NULL,'category_id' => NULL,'featured' => '0','menu_status' => '0','status' => '1','lang' => 'en','created_at' => now(),'updated_at' => now()),
            array('id' => '22','name' => 'Fast Payment and receving system','slug' => NULL,'type' => 'member_benefits','other' => NULL,'category_id' => NULL,'featured' => '0','menu_status' => '0','status' => '1','lang' => 'en','created_at' => now(),'updated_at' => now()),
            array('id' => '23','name' => 'كسب ما يصل إلى 0.25 دولار لكل نقرة','slug' => NULL,'type' => 'member_benefits','other' => NULL,'category_id' => NULL,'featured' => '0','menu_status' => '0','status' => '1','lang' => 'ar','created_at' => now(),'updated_at' => now()),
            array('id' => '24','name' => 'اكسب ما يصل إلى 0.28 دولار لكل نقرة إحالة','slug' => NULL,'type' => 'member_benefits','other' => NULL,'category_id' => NULL,'featured' => '0','menu_status' => '0','status' => '1','lang' => 'ar','created_at' => now(),'updated_at' => now()),
            array('id' => '25','name' => 'نظام الدفع والاستلام السريع','slug' => NULL,'type' => 'member_benefits','other' => NULL,'category_id' => NULL,'featured' => '0','menu_status' => '0','status' => '1','lang' => 'ar','created_at' => now(),'updated_at' => now()),
            array('id' => '26','name' => 'كسب ما يصل إلى 0.25 دولار لكل نقرة','slug' => NULL,'type' => 'member_benefits','other' => NULL,'category_id' => NULL,'featured' => '0','menu_status' => '0','status' => '1','lang' => 'ar','created_at' => now(),'updated_at' => now()),
            array('id' => '27','name' => 'اكسب ما يصل إلى 0.28 دولار لكل نقرة إحالة','slug' => NULL,'type' => 'member_benefits','other' => NULL,'category_id' => NULL,'featured' => '0','menu_status' => '0','status' => '1','lang' => 'ar','created_at' => now(),'updated_at' => now()),
            array('id' => '28','name' => 'نظام الدفع والاستلام السريع','slug' => NULL,'type' => 'member_benefits','other' => NULL,'category_id' => NULL,'featured' => '0','menu_status' => '0','status' => '1','lang' => 'ar','created_at' => now(),'updated_at' => now()),
            array('id' => '29','name' => 'Members Info','slug' => NULL,'type' => 'heading.member_info','other' => 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Doloribus necessitatibus repudiandae porro reprehenderit up','category_id' => NULL,'featured' => '0','menu_status' => '0','status' => '1','lang' => 'en','created_at' => now(),'updated_at' => now()),
            array('id' => '30','name' => 'Advertise Benefit','slug' => NULL,'type' => 'heading.advertise_benefits','other' => 'Ipsum dolor sit amet consectetur adipisicing elit. Aspernatur quaerat laudantium error assumenda ratione tempora nemo modi maxime! Corrupti,','category_id' => NULL,'featured' => '0','menu_status' => '0','status' => '1','lang' => 'en','created_at' => now(),'updated_at' => now()),
            array('id' => '31','name' => 'Advertise to your Website. With real time insights into every penny spent.','slug' => NULL,'type' => 'advertise_benefits','other' => 'Ipsum dolor sit amet consectetur adipisicing elit. Aspernatur quaerat laudantium error assumenda ratione tempora nemo modi maxime! Corrupti,','category_id' => NULL,'featured' => '1','menu_status' => '0','status' => '1','lang' => 'en','created_at' => now(),'updated_at' => now()),
            array('id' => '32','name' => 'Advertise to your Website. With real time insights into every penny spent.','slug' => NULL,'type' => 'advertise_benefits','other' => 'Ipsum dolor sit amet consectetur adipisicing elit. Aspernatur quaerat laudantium error assumenda ratione tempora nemo modi maxime! Corrupti,','category_id' => NULL,'featured' => '1','menu_status' => '0','status' => '1','lang' => 'en','created_at' => now(),'updated_at' => now()),
            array('id' => '33','name' => 'Ipsum dolor sit amet consectetur adipisicing elit.','slug' => NULL,'type' => 'advertise_benefits','other' => 'Ipsum dolor sit amet consectetur adipisicing elit. Aspernatur quaerat laudantium error assumenda ratione tempora nemo modi maxime! Corrupti, praesentium! Lorem ipsum dolor sit amet consectetur adipisicing elit. Numquam consequuntur.','category_id' => NULL,'featured' => '1','menu_status' => '0','status' => '1','lang' => 'en','created_at' => now(),'updated_at' => now()),
            array('id' => '34','name' => 'Top Payouts','slug' => NULL,'type' => 'heading.payouts','other' => 'That Gives E-Commerce Businesses The Power To Accept Digital Currencies - And Get All The Benefits You Can’t With Just Traditional Payment Methods.','category_id' => NULL,'featured' => '0','menu_status' => '0','status' => '1','lang' => 'en','created_at' => now(),'updated_at' => now()),
            array('id' => '35','name' => 'Jhone Doe','slug' => NULL,'type' => 'team_members','other' => 'CEO','category_id' => NULL,'featured' => '1','menu_status' => '0','status' => '1','lang' => 'en','created_at' => now(),'updated_at' => now()),
            array('id' => '36','name' => 'Jane Doe','slug' => NULL,'type' => 'team_members','other' => 'CO Founder','category_id' => NULL,'featured' => '1','menu_status' => '0','status' => '1','lang' => 'en','created_at' => now(),'updated_at' => now()),
            array('id' => '37','name' => 'Clinton Doe','slug' => NULL,'type' => 'team_members','other' => 'Financial Officer','category_id' => NULL,'featured' => '1','menu_status' => '0','status' => '1','lang' => 'en','created_at' => now(),'updated_at' => now()),
            array('id' => '38','name' => 'Pagla Doe','slug' => NULL,'type' => 'team_members','other' => 'Advertising Manager','category_id' => NULL,'featured' => '1','menu_status' => '0','status' => '1','lang' => 'en','created_at' => now(),'updated_at' => now()),
            array('id' => '39','name' => 'level 0','slug' => 'percentage','type' => 'ReferralCommission','other' => '0','category_id' => NULL,'featured' => '0','menu_status' => '0','status' => '1','lang' => 'en','created_at' => now(),'updated_at' => now()),
            array('id' => '40','name' => 'level 1','slug' => 'percentage','type' => 'ReferralCommission','other' => '1','category_id' => NULL,'featured' => '0','menu_status' => '0','status' => '1','lang' => 'en','created_at' => now(),'updated_at' => now()),
            array('id' => '41','name' => 'View Advertise & Earn Money','slug' => NULL,'type' => 'heading.earn_money','other' => 'That Gives E-Commerce Businesses The Power To Accept Digital Currencies - And Get All The Benefits You Can’t With Just Traditional Payment Methods.','category_id' => NULL,'featured' => '0','menu_status' => '0','status' => '1','lang' => 'en','created_at' => now(),'updated_at' => now()),
            array('id' => '42','name' => 'COME AND JOIN US TODAY','slug' => NULL,'type' => 'heading.join_us','other' => 'Discover how much money you can earn','category_id' => NULL,'featured' => '0','menu_status' => '0','status' => '1','lang' => 'en','created_at' => now(),'updated_at' => now()),
            array('id' => '43','name' => 'Our Team','slug' => NULL,'type' => 'heading.our_team','other' => 'That Gives E-Commerce Businesses The Power To Accept Digital Currencies - And Get All The Benefits You Can’t With Just Traditional Payment Methods.','category_id' => NULL,'featured' => '0','menu_status' => '0','status' => '1','lang' => 'en','created_at' => now(),'updated_at' => now()),
            array('id' => '44','name' => 'Top Investor','slug' => NULL,'type' => 'heading.top_investor','other' => 'That Gives E-Commerce Businesses The Power To Accept Digital Currencies - And Get All The Benefits You Can’t With Just Traditional Payment Methods.','category_id' => NULL,'featured' => '0','menu_status' => '0','status' => '1','lang' => 'en','created_at' => now(),'updated_at' => now()),
            array('id' => '45','name' => 'Client Reviews','slug' => NULL,'type' => 'heading.client_review','other' => 'That Gives E-Commerce Businesses The Power To Accept Digital Currencies - And Get All The Benefits You Can’t With Just Traditional Payment Methods.','category_id' => NULL,'featured' => '0','menu_status' => '0','status' => '1','lang' => 'en','created_at' => now(),'updated_at' => now()),
            array('id' => '46','name' => 'Blog News','slug' => NULL,'type' => 'heading.blog_news','other' => 'That Gives E-Commerce Businesses The Power To Accept Digital Currencies - And Get All The Benefits You Can’t With Just Traditional Payment Methods.','category_id' => NULL,'featured' => '0','menu_status' => '0','status' => '1','lang' => 'en','created_at' => now(),'updated_at' => now()),
            array('id' => '47','name' => 'Contact With Us','slug' => NULL,'type' => 'heading.contact','other' => 'That Gives E-Commerce Businesses The Power To Accept Digital Currencies - And Get All The Benefits You Can’t With Just Traditional Payment Methods.','category_id' => NULL,'featured' => '0','menu_status' => '0','status' => '1','lang' => 'en','created_at' => now(),'updated_at' => now()),
            array('id' => '48','name' => 'Membership Plans','slug' => NULL,'type' => 'heading.price_plan','other' => 'That Gives E-Commerce Businesses The Power To Accept Digital Currencies - And Get All The Benefits You Can’t With Just Traditional Payment Methods.','category_id' => NULL,'featured' => '0','menu_status' => '0','status' => '1','lang' => 'en','created_at' => now(),'updated_at' => now()),
            array('id' => '49','name' => 'A Frequently Asked Questions','slug' => NULL,'type' => 'heading.faq','other' => 'That Gives E-Commerce Businesses The Power To Accept Digital Currencies - And Get All The Benefits You Can’t With Just Traditional Payment Methods.','category_id' => NULL,'featured' => '0','menu_status' => '0','status' => '1','lang' => 'en','created_at' => now(),'updated_at' => now()),
            array('id' => '50','name' => 'Jonaton Tadsra','slug' => '4.7','type' => 'review','other' => NULL,'category_id' => NULL,'featured' => '0','menu_status' => '0','status' => '1','lang' => 'en','created_at' => now(),'updated_at' => now()),
            array('id' => '51','name' => 'Tucker Olsen','slug' => '3.2','type' => 'review','other' => NULL,'category_id' => NULL,'featured' => '0','menu_status' => '0','status' => '1','lang' => 'en','created_at' => now(),'updated_at' => now()),
            array('id' => '52','name' => 'Xantha Klein','slug' => '5','type' => 'review','other' => NULL,'category_id' => NULL,'featured' => '0','menu_status' => '0','status' => '1','lang' => 'en','created_at' => now(),'updated_at' => now()),
            array('id' => '53','name' => 'Rhiannon Skinner','slug' => '4.1','type' => 'review','other' => NULL,'category_id' => NULL,'featured' => '0','menu_status' => '0','status' => '1','lang' => 'en','created_at' => now(),'updated_at' => now()),
            array('id' => '54','name' => 'Mira Carver','slug' => '2','type' => 'review','other' => NULL,'category_id' => NULL,'featured' => '0','menu_status' => '0','status' => '1','lang' => 'en','created_at' => now(),'updated_at' => now()),
            array('id' => '55','name' => 'Irma Burgess','slug' => '2','type' => 'review','other' => NULL,'category_id' => NULL,'featured' => '0','menu_status' => '0','status' => '1','lang' => 'en','created_at' => now(),'updated_at' => now()),
            array('id' => '56','name' => 'Calista Cummings','slug' => '3','type' => 'review','other' => NULL,'category_id' => NULL,'featured' => '0','menu_status' => '0','status' => '1','lang' => 'en','created_at' => now(),'updated_at' => now()),
            array('id' => '57','name' => 'Gretchen Wilcox','slug' => NULL,'type' => 'top_investors','other' => '320','category_id' => NULL,'featured' => '1','menu_status' => '0','status' => '1','lang' => 'en','created_at' => now(),'updated_at' => now()),
            array('id' => '58','name' => 'Barbara Branch','slug' => NULL,'type' => 'top_investors','other' => '95','category_id' => NULL,'featured' => '1','menu_status' => '0','status' => '1','lang' => 'en','created_at' => now(),'updated_at' => now()),
            array('id' => '59','name' => 'Nathan Battle','slug' => NULL,'type' => 'top_investors','other' => '650','category_id' => NULL,'featured' => '1','menu_status' => '0','status' => '1','lang' => 'en','created_at' => now(),'updated_at' => now()),
            array('id' => '60','name' => 'Xena Booth','slug' => NULL,'type' => 'top_investors','other' => '720','category_id' => NULL,'featured' => '1','menu_status' => '0','status' => '1','lang' => 'en','created_at' => now(),'updated_at' => now()),
            array('id' => '61','name' => 'Gretchen Rosario','slug' => NULL,'type' => 'top_investors','other' => '1000','category_id' => NULL,'featured' => '0','menu_status' => '0','status' => '1','lang' => 'en','created_at' => now(),'updated_at' => now()),
            array('id' => '62','name' => 'Martin Romero','slug' => NULL,'type' => 'top_investors','other' => '440','category_id' => NULL,'featured' => '1','menu_status' => '0','status' => '1','lang' => 'en','created_at' => now(),'updated_at' => now()),
            array('id' => '63','name' => 'How to Deposit Money?','slug' => NULL,'type' => 'faq','other' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quae quidem blanditiis delectus corporis, possimus officia sint sequi ex tenetur id impedit est pariatur iure animi non a ratione reiciendis nihil sed consequatur atque repellendus fugit perspiciat','category_id' => NULL,'featured' => '0','menu_status' => '0','status' => '1','lang' => 'en','created_at' => now(),'updated_at' => now()),
            array('id' => '64','name' => 'How Does the PTC MLM Plan Works?','slug' => NULL,'type' => 'faq','other' => 'Non porttitor integer a tortor suspendisse mattis turpis dolor at porta tincidunt ex pulvinar nisl ullamcorper cras maecenas dictum diam morbi iaculis accumsan ligula nascetur tempor vitae fringilla parturient lobortis donec elementum litora duis malesuad','category_id' => NULL,'featured' => '0','menu_status' => '0','status' => '1','lang' => 'en','created_at' => now(),'updated_at' => now()),
            array('id' => '65','name' => 'Benefits of Binary MLM Plan','slug' => NULL,'type' => 'faq','other' => 'Accumsan ultricies integer facilisi lobortis tellus purus maecenas aenean natoque tortor tempor letius vivamus inceptos turpis lacus si consectetuer condimentum rhoncus curae molestie felis pretium rutrum sed dolor facilisis dis nibh euismod ad vitae null','category_id' => NULL,'featured' => '0','menu_status' => '0','status' => '1','lang' => 'en','created_at' => now(),'updated_at' => now()),
            array('id' => '66','name' => 'I have not received my withdrawal','slug' => NULL,'type' => 'faq','other' => 'Dictum taciti leo lobortis viverra lacinia libero ipsum facilisi dignissim metus parturient natoque feugiat ultricies netus malesuada dictumst sagittis egestas arcu tellus id augue semper ullamcorper convallis blandit aptent senectus venenatis cubilia hab','category_id' => NULL,'featured' => '0','menu_status' => '0','status' => '1','lang' => 'en','created_at' => now(),'updated_at' => now()),
            array('id' => '67','name' => 'How to making a withdrawal?','slug' => NULL,'type' => 'faq','other' => 'Risus convallis efficitur dignissim iaculis dis rutrum senectus purus in dictumst torquent pharetra litora facilisis et tincidunt dui scelerisque cursus morbi lobortis letius vehicula augue nibh primis ex congue sollicitudin odio taciti nisi amet eu vel m','category_id' => NULL,'featured' => '0','menu_status' => '0','status' => '1','lang' => 'en','created_at' => now(),'updated_at' => now()),
            array('id' => '68','name' => 'How to making a Payouts?','slug' => NULL,'type' => 'faq','other' => 'Aliquet tincidunt venenatis tellus semper ultricies eu aenean dictum class nisi est nostra condimentum ipsum consectetuer pharetra taciti duis iaculis tortor nulla dui fames nisl placerat consequat bibendum egestas faucibus hendrerit suscipit porttitor im','category_id' => NULL,'featured' => '0','menu_status' => '0','status' => '1','lang' => 'en','created_at' => now(),'updated_at' => now())
          );


        Category::insert($categories);
    }
}
